### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by Konjiki-no-Yami** [Supportux/supportux.github.io#2]
I executed `# pacman -Syyu` and `# yaourt -Syua` multiple times but it gets stuck at the `extra.db` database. `core.db` updates okay.
So I went to my closest mirror in the web browser and apparently [ftp://ftp.belnet.be/mirror/manjaro/stable/extra/x86_64/extra.db](url) is an empty file.
Any idea what happened to it?

**Comment by badbodh** [comment]
Nope. Ask in forum. We're just a bunch of hooligans here.

It happens when mirrors are syncing. Give it some time. Or use another mirror.

**Comment by Konjiki-no-Yami** [comment]
Fixed the issue by issuing `pacman -Syu` while having the mirrorlist next to it in nano.
Found a working local server which I now set to use that one exclusively. Thanks anyway!

**Comment by badbodh** [comment]
^ ignore all that, i'm just hammering around. Will probably delete this if i can figure out how.
But please go ask in forum.manjaro.org from now on.

**Comment by Konjiki-no-Yami** [comment]
Yea ok but just delete it next time
